<?php

/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function openattribute_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/openattribute':
      return t('Choose Creative Commons license to attach to nodes.');
    case "admin/help#openattribute":
      return t("Attach a Creative Commons license to a node within Drupal can designate the content of that node, as well as any attached files, as available under that license.");
  }
}

/**
 * Implementation of hook_perm().
 */
function openattribute_perm() {
  return array('administer openattribute');
}

/**
 * Implementation of hook_menu().
 */
function openattribute_menu() {
  $items = array();
  $items['admin/settings/openattribute'] = array(
    'title' => 'OpenAttribute',
    'description' => 'Configure attribution settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openattribute_settings_form'),
    'access arguments' => array('administer openattribute'),
  );
  $items['admin/settings/openattribute/edit'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );

  $items['admin/settings/openattribute/site'] = array(
    'title' => 'Site license',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openattribute_configure_site'),
    'access arguments' => array('administer openattribute'),
    'type' => MENU_LOCAL_TASK
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function openattribute_theme() {
  return array(
    'openattribute_user_admin_account' => array(
      'arguments' => array('form' => NULL),
      'file' => 'user.admin.inc',
    ),
  );
}

